import { Genre } from "../utils/types";

export const MOVIE_GENRES_LIST: Genre[] = [
  { id: 28, key: "action", name: "Action" },
  { id: 12, key: "adventure", name: "Adventure" },
  { id: 16, key: "animation", name: "Animation" },
  { id: 35, key: "comedy", name: "Comedy" },
  { id: 80, key: "crime", name: "Crime" },
  { id: 99, key: "documentary", name: "Documentary" },
  { id: 18, key: "drama", name: "Drama" },
  { id: 14, key: "fantasy", name: "Fantasy" },
  { id: 10751, key: "family", name: "Family" },
  { id: 27, key: "horror", name: "Horror" },
  { id: 36, key: "history", name: "History" },
  { id: 10402, key: "music", name: "Music" },
  { id: 9648, key: "mystery", name: "Mystery" },
  { id: 10749, key: "romance", name: "Romance" },
  { id: 878, key: "scienceFiction", name: "Science Fiction" },
  { id: 53, key: "thriller", name: "Thriller" },
  { id: 10752, key: "war", name: "War" },
  { id: 37, key: "western", name: "Western" },
];

export const TV_GENRES_LIST: Genre[] = [
  { id: 10759, key: "actionAdventure", name: "Action & Adventure" },
  { id: 16, key: "animation", name: "Animation" },
  { id: 35, key: "comedy", name: "Comedy" },
  { id: 80, key: "crime", name: "Crime" },
  { id: 99, key: "documentary", name: "Documentary" },
  { id: 18, key: "drama", name: "Drama" },
  { id: 10751, key: "family", name: "Family" },
  { id: 10762, key: "kids", name: "Kids" },
  { id: 9648, key: "mystery", name: "Mystery" },
  { id: 10763, key: "news", name: "News" },
  { id: 10764, key: "reality", name: "Reality" },
  { id: 10765, key: "sciFiFantasy", name: "Sci-Fi & Fantasy" },
  { id: 10766, key: "soap", name: "Soap" },
  { id: 10767, key: "talk", name: "Talk" },
  { id: 10768, key: "warPolitics", name: "War & Politics" },
  { id: 37, key: "western", name: "Western" },
];
